--1. Base de Datos Oracle 19c
--Crear Tabla
CREATE TABLE CLIENTES_J
(
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR2(100),
    EMAIL VARCHAR2(100),
    TELEFONO VARCHAR2(20),

    CONSTRAINT PK_CLIENTES_J
    PRIMARY KEY(ID)
);

COMMIT;

--Datos de Prueba
INSERT INTO CLIENTES_J(NOMBRE,EMAIL,TELEFONO)
VALUES('Juan Perez','juan@gmail.com','3001111111');

INSERT INTO CLIENTES_J(NOMBRE,EMAIL,TELEFONO)
VALUES('Maria Gomez','maria@gmail.com','3002222222');

COMMIT;